import { createDemoEngine } from './src/core/simulationEngine.js';

export function initCircuitLab(){
const engine=createDemoEngine();
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const components={BASIC:[['R','Resistor'],['C','Capacitor'],['L','Inductor'],['D','Diode'],['▣','LED']],SEMICONDUCTORS:[['Q','Transistor'],['▰','MOSFET'],['△','OpAmp'],['▥','Voltage Regulator']],DIGITAL:[['&','Logic Gate'],['⊕','Flip Flop'],['#','Counter']],MICROCONTROLLERS:[['▣','Arduino UNO'],['◈','ESP32'],['μ','ATmega']],OUTPUT:[['●','LED'],['▥','LCD Display'],['▦','7 Segment'],['◉','Motor'],['♪','Buzzer']],INSTRUMENTS:[['⌁','Oscilloscope'],['Ω','Multimeter'],['∿','Signal Generator']]};
function renderComponents(filter=''){let html='';Object.entries(components).forEach(([group,items])=>{let found=items.filter(x=>x[1].toLowerCase().includes(filter.toLowerCase()));if(found.length){html+=`<div class="comp-group">${group}</div>`+found.map(x=>`<div class="component-item" draggable="true" data-name="${x[1]}"><span class="comp-symbol">${x[0]}</span>${x[1]}</div>`).join('')}});$('#componentList').innerHTML=html}
renderComponents();$('#componentSearch').oninput=e=>renderComponents(e.target.value);
$$('.activity').forEach(btn=>btn.onclick=()=>{ $$('.activity').forEach(x=>x.classList.remove('active'));btn.classList.add('active');let p=btn.dataset.panel;$('#panelTitle').textContent=p==='components'?'COMPONENTS':p==='code'?'SOURCE CONTROL':'EXPLORER';['explorerPanel','componentsPanel','codePanel'].forEach(x=>$('#'+x).classList.add('hidden'));if(p==='components')$('#componentsPanel').classList.remove('hidden');else if(p==='code')$('#codePanel').classList.remove('hidden');else $('#explorerPanel').classList.remove('hidden')});
let running=false,timer;engine.subscribe(s=>{ if(s.status==='running') setRunningUi(true,s); });function setRunningUi(v,s){let state=$('.sim-state');state.classList.toggle('running',v);state.classList.toggle('stopped',!v);state.innerHTML=`<b></b> ${v?'RUNNING':'STOPPED'}`;$('#runBtn').innerHTML=v?'Ⅱ <span>Pause</span>':'▶ <span>Run</span>';$('#ledWire').classList.toggle('active',v);document.querySelector('.led-ring').style.fill=v?'#b32638':'#3b171d';document.querySelector('.light-rays').style.opacity=v?'1':'.25';document.querySelector('.led .sub').textContent=v?'RED · ON':'RED · OFF';$('#meterValue').textContent=v?'5.02':'0.00';$('#meterStatus').textContent=v?'MEASURING':'READY';if(v){$('.log').innerHTML='<span class="log-time">14:32:10</span><span class="ok">✓</span> Simulation started <span class="sep">·</span> D13 → HIGH <span class="sep">·</span> LED1 → ON <span class="cursor">▌</span>'}else $('.log').innerHTML='<span class="log-time">14:32:11</span><span class="ok">✓</span> Simulation stopped <span class="cursor">▌</span>'}function setRunning(v){running=v;v?engine.start():engine.stop();setRunningUi(v,engine.getState());if(v){clearInterval(timer);timer=setInterval(()=>engine.step(0.08),80)}else clearInterval(timer)}$('#runBtn').onclick=()=>setRunning(!running);$('#pauseBtn').onclick=()=>{engine.pause();setRunningUi(false,engine.getState())};$('#stopBtn').onclick=()=>setRunning(false);$('#resetBtn').onclick=()=>{engine.reset();setRunningUi(false,engine.getState())};
$('#circuit').addEventListener('click',e=>{let c=e.target.closest('.component');if(!c)return;$$('.component').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');let name=c.dataset.component||'Component';$('#selectedName').textContent=name+' · Passive';if(name.includes('LED')){$('#refInput').value='LED1';$('#valueInput').value='RED';$('.component-symbol').textContent='◉'}else if(name.includes('Arduino')){$('#refInput').value='U1';$('#valueInput').value='UNO R3';$('.component-symbol').textContent='μ'}else{$('#refInput').value='R1';$('#valueInput').value='220';$('.component-symbol').textContent='R'}});
function palette(open){$('#palette').classList.toggle('hidden',!open);if(open)$('#commandInput').focus()}document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();palette(true)}if(e.key==='Escape')palette(false);if(e.key==='F6')setRunning(true);if(e.key.toLowerCase()==='f'&&!e.ctrlKey)e.preventDefault()});$('#palette').onclick=e=>{if(e.target.id==='palette')palette(false)};$$('.command-list button').forEach(b=>b.onclick=()=>{let c=b.dataset.cmd;if(c==='run')setRunning(true);if(c==='stop')setRunning(false);if(c==='save'){$('.modified').textContent='✓';$('.modified').style.color='var(--green)'}palette(false)});$('#commandInput').oninput=e=>{$$('.command-list button').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'flex':'none')};
$$('.tree-row.file').forEach(r=>r.onclick=()=>{$$('.tree-row.file').forEach(x=>x.classList.remove('selected'));r.classList.add('selected')});

}
