export default `
<div class="app-shell">
<header class="topbar">
  <div class="brand"><div class="brand-mark">⌬</div><div><strong>CircuitLab</strong><span>STUDIO</span></div></div>
  <div class="tabs"><button class="tab active"><span class="dot cyan"></span>main.sim <i>×</i></button><button class="tab"><span class="file-icon">▤</span>main.cpp <i>×</i></button><button class="add-tab">+</button></div>
  <div class="runbar"><span class="sim-state stopped"><b></b> STOPPED</span><button class="run primary" id="runBtn">▶ <span>Run</span></button><button class="tool" id="pauseBtn">Ⅱ</button><button class="tool" id="stopBtn">■</button><button class="tool" id="resetBtn">↻</button><div class="speed">1×⌄</div><button class="icon-btn" title="Settings">⚙</button></div>
</header>
<div class="workspace">
  <nav class="activitybar" aria-label="Activity bar"><button class="activity active" data-panel="explorer" title="Explorer">▤</button><button class="activity" data-panel="components" title="Components">◈</button><button class="activity" data-panel="circuit" title="Circuit view">⌁</button><button class="activity" data-panel="instruments" title="Instruments">⌁</button><button class="activity" data-panel="code" title="Code">{ }</button><div class="activity-spacer"></div><button class="activity" title="Extensions">▦</button><button class="activity" title="Settings">⚙</button></nav>
  <aside class="left-panel" id="leftPanel">
    <section class="panel-head"><span id="panelTitle">EXPLORER</span><div class="head-actions"><button title="New file">＋</button><button>⋯</button></div></section>
    <div id="explorerPanel" class="panel-content"><div class="project-title"><span>⌄</span> CIRCUITLAB DEMO <small>⋯</small></div><div class="tree"><div class="tree-row folder"><span>⌄</span> circuits</div><div class="tree-row file selected"><span class="file-dot"></span> main.sim <em>●</em></div><div class="tree-row file"><span class="file-dot amber"></span> power.sim</div><div class="tree-row folder"><span>›</span> src</div><div class="tree-row file"><span class="file-dot purple"></span> main.cpp</div><div class="tree-row file"><span class="file-dot purple"></span> motor.cpp</div><div class="tree-row folder"><span>›</span> components</div><div class="tree-row file"><span class="readme">▤</span> README.md</div></div><div class="explorer-bottom"><div class="project-title"><span>⌄</span> OUTLINE</div><p class="muted">No symbols found</p><div class="project-title"><span>⌄</span> TIMELINE</div></div></div>
    <div id="componentsPanel" class="panel-content hidden"><div class="search"><span>⌕</span><input id="componentSearch" placeholder="Search components..."/></div><div class="component-groups" id="componentList"></div></div>
    <div id="codePanel" class="panel-content hidden"><div class="search"><span>⌕</span><input placeholder="Search files..."/></div><div class="tree"><div class="tree-row file selected"><span class="file-dot purple"></span> main.cpp</div><div class="tree-row file"><span class="file-dot purple"></span> motor.cpp</div></div></div>
  </aside>
  <main class="main-area">
    <div class="editor-toolbar"><div class="breadcrumbs"><span>circuits</span><b>›</b><strong>main.sim</strong><span class="modified">●</span></div><div class="canvas-tools"><button class="tool-toggle active">▦ <span>Grid</span></button><button class="tool-toggle active">⌗ <span>Snap</span></button><button title="Zoom out">−</button><span class="zoom">100%</span><button title="Zoom in">＋</button><button title="Fit circuit">⛶</button></div></div>
    <div class="canvas-wrap" id="canvasWrap"><svg id="circuit" viewBox="0 0 1000 600" role="img" aria-label="Circuit canvas"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1.5" cy="1.5" r="1" fill="#27313d"/></pattern><filter id="glow"><feGaussianBlur stdDeviation="3" result="coloredBlur"/><feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="1000" height="600" fill="url(#grid)"/><g class="wire-layer"><path class="wire power" d="M210 170 H360 V250"/><path class="wire power" d="M360 250 H465"/><path class="wire signal" id="ledWire" d="M535 250 H660 V340"/><path class="wire ground" d="M660 390 V470 H535"/><path class="wire ground" d="M660 470 H360 V390"/></g><g class="labels"><text x="305" y="157">+5V</text><text x="585" y="235">D13</text><text x="674" y="475">GND</text></g><g class="component arduino" data-component="Arduino UNO"><rect x="95" y="150" width="115" height="240" rx="5"/><rect x="108" y="175" width="52" height="100" rx="2" class="chip"/><text x="108" y="310">ARDUINO</text><text x="108" y="328" class="sub">UNO R3</text><circle cx="210" cy="170" r="5" class="pin digital"/><circle cx="210" cy="250" r="5" class="pin digital"/><text x="178" y="165" class="pin-label">VIN</text><text x="172" y="245" class="pin-label">D13</text><text x="119" y="195" class="chip-text">ATmega328P</text></g><g class="component resistor" data-component="Resistor R1"><rect x="360" y="235" width="105" height="30" rx="4"/><path d="M375 250 l10 -12 10 24 10 -24 10 24 10 -24 10 24 10 -12"/><text x="382" y="292">R1</text><text x="382" y="308" class="sub">220 Ω</text><circle cx="360" cy="250" r="5" class="pin"/><circle cx="465" cy="250" r="5" class="pin"/></g><g class="component led" data-component="LED1"><circle cx="500" cy="250" r="35" class="led-ring"/><path d="M486 264 l28 -28 M500 278 v-56 M514 264 l-28 -28"/><path d="M516 215 l10 -10 M520 224 l13 -5" class="light-rays"/><text x="482" y="310">LED1</text><text x="480" y="326" class="sub">RED · OFF</text><circle cx="535" cy="250" r="5" class="pin"/></g><g class="component ground-symbol"><path d="M660 470 v18 m-20 0 h40 m-13 8 h26 m-12 8 h12"/><text x="675" y="515">GND</text></g><g class="selection" id="selection"><rect x="345" y="220" width="140" height="65" rx="5"/></g></svg><div class="canvas-hint">Click a component to inspect · <kbd>W</kbd> wire · <kbd>R</kbd> rotate</div><div class="minimap"><span>MAIN.SIM</span><div class="mini-circuit"></div></div></div>
    <div class="bottom-panel"><div class="bottom-tabs"><button class="active">PROBLEMS <b>0</b></button><button>OUTPUT</button><button>TERMINAL</button><button>SERIAL</button><button>VARIABLES</button><span class="panel-chevron">⌄</span></div><div class="log"><span class="log-time">14:32:08</span><span class="ok">✓</span> Circuit loaded <span class="sep">·</span><span class="log-time">14:32:09</span> Arduino UNO initialized <span class="cursor">▌</span></div></div>
  </main>
  <aside class="right-panel"><section class="panel-head"><span>INSPECTOR</span><button>⋯</button></section><div class="inspector" id="inspector"><div class="selection-title"><div class="component-symbol">R</div><div><strong>RESISTOR</strong><span id="selectedName">R1 · Passive</span></div><button>⋯</button></div><div class="prop-group"><div class="prop-title">GENERAL <span>⌃</span></div><label>Reference<input id="refInput" value="R1"/></label><label>Value<div class="value-input"><input id="valueInput" value="220 Ω"/><span>Ω</span></div></label><label>Tolerance<input value="±5%"/></label></div><div class="prop-group"><div class="prop-title">TRANSFORM <span>⌃</span></div><div class="two-col"><label>X<input value="360"/></label><label>Y<input value="250"/></label></div><label>Rotation<div class="value-input"><input value="0"/><span>°</span></div></label></div><div class="prop-group"><div class="prop-title">SIMULATION <span>⌃</span></div><label>Initial state<select><option>Passive</option><option>Active</option></select></label><label>Temperature<input value="25 °C"/></label></div></div><div class="instrument-card"><div class="instrument-title"><span>◒</span> MULTIMETER <i>•••</i></div><div class="meter-reading"><strong id="meterValue">0.00</strong><span>V</span></div><div class="meter-modes"><button class="active">V DC</button><button>V AC</button><button>A</button><button>Ω</button></div><div class="meter-status"><span class="probe red"></span> COM <span class="probe black"></span> INPUT <em id="meterStatus">READY</em></div></div></aside>
</div>
<div class="statusbar"><span class="branch">⌘ main</span><span>◉ 0 errors</span><span>↯ 0 warnings</span><span class="status-spacer"></span><span>Ln 1, Col 1</span><span>UTF-8</span><span>Spaces: 2</span><span>⚡ CircuitLab Engine</span></div>
<div class="palette hidden" id="palette"><div class="palette-box"><div class="palette-search">⌕ <input autofocus placeholder="Search commands..." id="commandInput"/></div><div class="command-list"><button data-cmd="run">▶ <span>Run Simulation</span><kbd>F6</kbd></button><button data-cmd="stop">■ <span>Stop Simulation</span></button><button data-cmd="resistor">＋ <span>Add Resistor</span><kbd>R</kbd></button><button data-cmd="oscilloscope">⌁ <span>Open Oscilloscope</span></button><button data-cmd="fit">⛶ <span>Zoom to Fit</span><kbd>F</kbd></button><button data-cmd="save">▣ <span>Save Project</span><kbd>⌘ S</kbd></button></div><div class="palette-footer">↑↓ Navigate <span>↵ Select</span><span>Esc Close</span></div></div></div>

`;
